import type { Metadata } from 'next';

import RecoilRootWrapper from '@recoil/RecoilRootWrapper';
import StyledComponentsRegistry from '@/lib/StyledComponentsRegistry';
import Header from '@components/layout/Header';
import { Wrapper } from '@components/styled/StyledComponents';
import { SocketProvider } from '@lib/SocketProvider';

export const metadata: Metadata = {
  title: 'coin-lab',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <SocketProvider>
        <body>
          <RecoilRootWrapper>
            <StyledComponentsRegistry>
              <Header />
              <Wrapper>{children}</Wrapper>
            </StyledComponentsRegistry>
          </RecoilRootWrapper>
        </body>
      </SocketProvider>
    </html>
  );
}
